//! Machined, renderer-agnostic controls and the common Poolrooms visual language.
//!
//! Call [`install`] once for each `egui::Context` before constructing the UI.
//! It installs the embedded typefaces, palette, spacing, and widget visuals.
//!
//! [`Rail`], [`DateSpool`], [`Checkbox`], [`Monoglyph`], [`CornerClose`],
//! [`DragHandle`], [`ForgePin`], [`LonginusCursor`], [`NumberInput`],
//! [`ScrewScroll`], and [`SortToggle`] are the crafted mechanisms. They return
//! richer response types that expose ordinary interaction state and the water
//! forcing generated by their moving solids. Applications using the optional
//! `water` feature pass those responses to the corresponding methods on
//! `water::Surface` during the same UI pass.
//!
//! [`Section`] supplies the physical disclosure and complete-header Lockout
//! Grille used by application-level panel managers. [`MnemonicText`],
//! [`Monoglyph::show_in`], and [`Keycap`]
//! supply command legends; [`exact_activation`] gives button-like responses
//! exact, non-bleeding Enter/Space ownership. Command routing and panel
//! traversal remain outside Poolrooms.

use std::f32::consts::TAU;
use std::sync::Arc;

use egui::epaint::{FontColorTransferFunction, text::HintingTarget};
use egui::{Color32, FontData, FontDefinitions, FontFamily, FontTweak, RichText, Stroke, Vec2};

mod checkbox;
mod corner_close;
mod date_spool;
mod drag_handle;
mod forge_pin;
mod forged;
mod foundry;
mod legend;
mod lockout_grille;
mod longinus_cursor;
mod mechanism;
mod monoglyph;
mod number_input;
mod plunger;
mod rail;
mod screw_scroll;
mod section;
mod sort_toggle;
mod symbol;
mod typography;
mod wheel;

pub use checkbox::{Checkbox, CheckboxResponse, CheckboxWake, LabelSide};
pub use corner_close::{CornerClose, CornerCloseResponse, CornerCloseWake};
pub use date_spool::{
    DateReels, DateSpool, GregorianDay, LabelSpool, SpoolResponse, SpoolWake, take_date_spool_wheel,
};
pub use drag_handle::{DragHandle, DragHandleResponse, DragHandleWake};
pub use forge_pin::ForgePin;
pub use forged::{ForgedMesh, ForgedVertex};
pub use legend::{Keycap, MnemonicText};
pub use longinus_cursor::LonginusCursor;
pub use mechanism::{
    Coupled, CoupledResponse, CouplingGap, CouplingPort, CouplingPorts, CouplingTarget,
    MechanismSize,
};
pub use monoglyph::{Monoglyph, MonoglyphFinish, MonoglyphResponse, MonoglyphWake};
pub use number_input::{
    NumberBound, NumberInput, NumberInputResponse, NumberInputWake, NumberRefusal, WheelPlane,
};
pub use plunger::PlungerWake;
pub use rail::{Rail, RailResponse, RailWake, rail_u16, rail_u16_sized};
pub use screw_scroll::ScrewScroll;
pub use section::{FoldFlux, FoldWake, Section, SectionResponse, section};
pub use sort_toggle::{SortDetent, SortToggle, SortToggleResponse, SortToggleWake};
pub use symbol::Symbol;

/// Calendar transport response; retained for existing date-spool callers.
pub type DateSpoolResponse = SpoolResponse;
/// Calendar transport displacement; retained for existing date-spool callers.
pub type DateWake = SpoolWake;
pub use typography::{FontScale, TypeRole, spatial_font, spatial_font_in};
pub use wheel::take_control_wheel;

#[cfg(feature = "foundry-atelier")]
pub(crate) use foundry::{DieTopology, StudyEtch, StudyEtchPalette};
#[cfg(feature = "foundry-atelier")]
pub(crate) use monoglyph::paint_study_etch;

const CMU_TYPEWRITER_LIGHT: &[u8] = include_bytes!("../assets/fonts/cmu-typewriter/cmunbtl.otf");
const NOTO_MATH: &[u8] = include_bytes!("../assets/fonts/noto/NotoSansMath-Regular.ttf");
const NOTO_SYMBOLS: &[u8] = include_bytes!("../assets/fonts/noto/NotoSansSymbols2-Regular.ttf");
const NOTO_GEAR: &[u8] = include_bytes!("../assets/fonts/noto/NotoSansSymbols-Gear.ttf");

const FACE_TEXT: &str = "cmu-typewriter-light";
const FACE_MATH: &str = "noto-sans-math";
const FACE_SYMBOLS: &str = "noto-sans-symbols-2";

// Ink and lamplight: warm charcoal paper, bone text, umber edges, lamplight
// amber for the accent, typewriter-ribbon red for repulsion — tuned to sit
// with the Computer Modern typewriter lineage instead of fighting it.
pub const INSPECTOR_WIDTH: f32 = 285.0;
/// Canonical clear span between twin-tied foundry parts.
///
/// Six points is twice the checkbox crown's nominal resting clearance inside
/// its socket. Identification plaques and coupled controls share this gauge.
pub const COUPLING_SPACING: f32 = 6.0;
pub const PAGE: Color32 = Color32::from_rgb(12, 11, 9);
pub const SURFACE: Color32 = Color32::from_rgb(17, 15, 12);
pub const RAISED: Color32 = Color32::from_rgb(36, 30, 22);
pub const CONTROL: Color32 = Color32::from_rgb(13, 12, 10);
pub const EDGE: Color32 = Color32::from_rgb(78, 66, 48);
pub const EDGE_STRONG: Color32 = Color32::from_rgb(142, 125, 100);
pub const TEXT: Color32 = Color32::from_rgb(226, 217, 198);
pub const MUTED: Color32 = Color32::from_rgb(158, 147, 128);
pub const HOT: Color32 = Color32::from_rgb(235, 197, 151);

/// Install the Poolrooms fonts, palette, spacing, and control visuals.
///
/// This replaces both egui theme slots and the context's font definitions, so
/// a later operating-system or browser theme notification cannot substitute
/// stock light chrome. Call it once after creating a context, and again only
/// if another subsystem later replaces those definitions.
pub fn install(ctx: &egui::Context) {
    install_fonts(ctx);
    let mut visuals = egui::Visuals::dark();
    visuals.text_options.color_transfer_function =
        FontColorTransferFunction::TwoCoverageMinusCoverageSq;
    visuals.panel_fill = PAGE;
    visuals.window_fill = SURFACE;
    visuals.faint_bg_color = CONTROL;
    visuals.extreme_bg_color = Color32::from_rgb(9, 8, 7);
    visuals.widgets.noninteractive.bg_fill = SURFACE;
    visuals.widgets.noninteractive.fg_stroke = Stroke::new(1.0_f32, MUTED);
    visuals.widgets.inactive.bg_fill = CONTROL;
    visuals.widgets.inactive.weak_bg_fill = CONTROL;
    visuals.widgets.inactive.fg_stroke = Stroke::new(1.0_f32, TEXT);
    visuals.widgets.inactive.bg_stroke = Stroke::new(1.0_f32, EDGE);
    visuals.widgets.hovered.bg_fill = RAISED;
    visuals.widgets.hovered.weak_bg_fill = RAISED;
    visuals.widgets.hovered.bg_stroke = Stroke::new(1.0_f32, EDGE_STRONG);
    visuals.widgets.active.bg_fill = Color32::from_rgb(44, 36, 25);
    visuals.widgets.active.weak_bg_fill = Color32::from_rgb(44, 36, 25);
    visuals.widgets.active.bg_stroke = Stroke::new(1.0_f32, HOT);
    visuals.selection.bg_fill = Color32::from_rgba_unmultiplied(226, 172, 106, 60);
    visuals.selection.stroke = Stroke::new(1.0_f32, HOT);
    visuals.hyperlink_color = HOT;
    visuals.window_stroke = Stroke::new(1.0_f32, EDGE_STRONG);
    // Near-flat: containers get 2px corners, widgets 1px.
    visuals.window_corner_radius = egui::CornerRadius::same(2);
    visuals.menu_corner_radius = egui::CornerRadius::same(2);
    for widget in [
        &mut visuals.widgets.noninteractive,
        &mut visuals.widgets.inactive,
        &mut visuals.widgets.hovered,
        &mut visuals.widgets.active,
        &mut visuals.widgets.open,
    ] {
        widget.corner_radius = egui::CornerRadius::same(1);
    }
    ctx.all_styles_mut(|style| {
        typography::install(style, FontScale::Standard);
        style.visuals = visuals.clone();
        style.spacing.item_spacing = Vec2::splat(6.0);
        style.spacing.button_padding = Vec2::new(7.0, 3.0);
        style.spacing.window_margin = egui::Margin::symmetric(8, 8);
        style.spacing.menu_margin = egui::Margin::symmetric(8, 8);
        style.spacing.indent = 12.0;
    });
}

/// Replace every semantic font metric with the selected pre-layout scale.
///
/// This rebuilds style-owned font identifiers; egui then lays out and
/// rasterizes text at the resulting point sizes. Physical pixels are never
/// resampled after rendering.
pub fn set_font_scale(ctx: &egui::Context, scale: FontScale) {
    let style = ctx.style_of(ctx.theme());
    if typography::active_scale(&style) == scale {
        return;
    }
    ctx.all_styles_mut(|style| typography::install(style, scale));
    ctx.request_repaint();
}

fn install_fonts(ctx: &egui::Context) {
    ctx.set_fonts(production_font_definitions());
}

/// Construct the exact production font stack for native renderer witnesses.
///
/// Applications must call [`install`] instead. This seam exists so the Font
/// Raster Atelier can add counterfactual families without approximating the
/// production definitions that remain responsible for its own interface.
#[doc(hidden)]
pub fn production_font_definitions() -> FontDefinitions {
    let mut fonts = FontDefinitions::empty();
    for (face, bytes) in [
        (FACE_TEXT, CMU_TYPEWRITER_LIGHT),
        (FACE_MATH, NOTO_MATH),
        (FACE_SYMBOLS, NOTO_SYMBOLS),
        ("noto-gear", NOTO_GEAR),
    ] {
        let data = FontData::from_static(bytes).tweak(production_font_tweak());
        let _old = fonts.font_data.insert(face.to_owned(), Arc::new(data));
    }
    for family in [FontFamily::Proportional, FontFamily::Monospace] {
        prepend_faces(
            &mut fonts,
            family,
            &[FACE_TEXT, FACE_MATH, FACE_SYMBOLS, "noto-gear"],
        );
    }
    fonts
}

fn production_font_tweak() -> FontTweak {
    FontTweak {
        hinting: Some(true),
        hinting_target: HintingTarget::Mono,
        subpixel_binning: Some(false),
        ..FontTweak::default()
    }
}

fn prepend_faces(fonts: &mut FontDefinitions, family: FontFamily, faces: &[&str]) {
    let stack = fonts.families.entry(family).or_default();
    for face in faces.iter().rev() {
        stack.retain(|name| name != face);
        stack.insert(0, (*face).to_owned());
    }
}

pub(crate) fn count_key_exact(
    input: &mut egui::InputState,
    modifiers: egui::Modifiers,
    key: egui::Key,
) -> usize {
    let mut count = 0;
    input.events.retain(|event| {
        let matched = matches!(
            event,
            egui::Event::Key {
                key: candidate,
                pressed: true,
                modifiers: held,
                ..
            } if *candidate == key && held.matches_exact(modifiers)
        );
        count += usize::from(matched);
        !matched
    });
    count
}

/// Adjudicate and seal one button-like egui response under Poolrooms key law.
///
/// Pointer, touch, and accessibility clicks remain activations. A focused
/// control admits only a fresh, unmodified Enter or Space key; accepted keys
/// and their repeats are consumed, while modified chords remain available to
/// their lawful owner. Disabled controls and controls behind a modal layer
/// never activate.
pub fn exact_activation(ui: &egui::Ui, response: &egui::Response) -> bool {
    let accessibility = ui.input_mut(|input| {
        let mut clicked = false;
        input.consume_accesskit_action_requests(response.id, |request| {
            let matches = request.action == egui::accesskit::Action::Click;
            clicked |= matches;
            matches
        });
        clicked
    });
    let admitted =
        response.enabled() && ui.memory(|memory| memory.is_above_modal_layer(response.layer_id));
    if !admitted {
        return false;
    }
    if response.clicked_by(egui::PointerButton::Primary) || accessibility {
        return true;
    }
    if !response.clicked() {
        return false;
    }
    let keyboard = ui.input(|input| {
        input.events.iter().any(|event| {
            matches!(
                event,
                egui::Event::Key {
                    key: egui::Key::Enter | egui::Key::Space,
                    pressed: true,
                    ..
                }
            )
        })
    });
    if !keyboard {
        return true;
    }
    ui.input_mut(|input| {
        let mut fresh = false;
        input.events.retain(|event| {
            let matched = matches!(
                event,
                egui::Event::Key {
                    key: egui::Key::Enter | egui::Key::Space,
                    pressed: true,
                    modifiers,
                    repeat,
                    ..
                } if modifiers.matches_exact(egui::Modifiers::NONE) && {
                    fresh |= !*repeat;
                    true
                }
            );
            !matched
        });
        fresh
    })
}

pub fn section_title(text: impl Into<String>) -> RichText {
    TypeRole::Heading.text(text).strong().color(HOT)
}

/// How fast tension grips and releases. Short, with a fast-rising ease so
/// the refraction reads as "on" the instant the pointer lands rather than
/// creeping up linearly.
const TENSION_TIME: f32 = 0.09;
const SHALLOW_GRIP: f32 = 0.42;
const TEXT_GRIP: f32 = 0.36;
const TEXT_PULSE_HZ: f32 = 0.3;

/// Puts a hovered widget "in tension": records a seed the water composite
/// turns into a refraction toward the pointer (blue bent hardest). The seed
/// is per-frame temp data; the boiler consumes it after the UI pass.
pub fn tension(ui: &egui::Ui, response: &egui::Response) {
    tension_with_grip(
        ui,
        response,
        response.hovered() || response.has_focus(),
        1.0,
        0.0,
    );
}

/// A gentler plate, for text-like controls that should breathe without
/// becoming full buttons in the water.
pub fn shallow_tension(ui: &egui::Ui, response: &egui::Response) {
    tension_with_grip(
        ui,
        response,
        response.hovered() || response.has_focus(),
        SHALLOW_GRIP,
        0.0,
    );
}

fn text_tension(ui: &egui::Ui, response: &egui::Response) {
    tension_with_grip(
        ui,
        response,
        response.has_focus(),
        TEXT_GRIP,
        TEXT_PULSE_HZ * TAU,
    );
}

fn tension_with_grip(
    ui: &egui::Ui,
    response: &egui::Response,
    held: bool,
    grip_scale: f32,
    omega: f32,
) {
    let grip = ui.ctx().animate_bool_with_time_and_easing(
        response.id.with("tension"),
        held,
        TENSION_TIME,
        egui::emath::easing::cubic_out,
    ) * grip_scale;
    if grip <= 0.0 {
        return;
    }
    let pointer = ui
        .ctx()
        .pointer_latest_pos()
        .unwrap_or_else(|| response.rect.center());
    crate::tide::push(
        ui.ctx(),
        response.id.value(),
        response.rect.shrink(1.0),
        pointer,
        grip,
        omega,
    );
}

pub fn hover_started(ui: &egui::Ui, response: &egui::Response) -> bool {
    let id = response.id.with("hover-started");
    ui.ctx().data_mut(|data| {
        let was = data.get_temp::<bool>(id).unwrap_or(false);
        let _old = data.insert_temp(id, response.hovered());
        response.hovered() && !was
    })
}

pub fn complete_chip(ui: &mut egui::Ui, text: RichText, selected: bool) -> egui::Response {
    let button = egui::Button::new(text.strong()).small();
    let button = if selected {
        button.fill(RAISED).stroke(Stroke::new(1.4_f32, HOT))
    } else {
        // Autocomplete has a real keyboard cursor. Do not let ordinary mouse
        // hover impersonate it: explicit fill/stroke keeps non-selected chips
        // visually quiet even when the pointer sits over the first candidate.
        button.fill(CONTROL).stroke(Stroke::new(1.0_f32, EDGE))
    };
    let response = ui.add(button);
    shallow_tension(ui, &response);
    response
}

#[derive(Clone, Copy, Debug)]
pub struct TextWake {
    pub rect: egui::Rect,
    flux: TextFlux,
}

impl TextWake {
    pub fn amp(self, unit: f32) -> f32 {
        match self.flux {
            TextFlux::Ink(mass) => unit * mass,
            TextFlux::Erase(mass) => unit * mass * 0.55,
        }
    }
}

#[derive(Clone, Copy, Debug)]
enum TextFlux {
    Ink(f32),
    Erase(f32),
}

pub fn text_wake(
    ui: &egui::Ui,
    response: &egui::Response,
    before: &str,
    after: &str,
) -> Option<TextWake> {
    text_tension(ui, response);
    if !response.changed() {
        return None;
    }
    let before = before.chars().collect::<Vec<_>>();
    let after = after.chars().collect::<Vec<_>>();
    if before == after {
        return None;
    }
    let head = before
        .iter()
        .zip(&after)
        .take_while(|(a, b)| a == b)
        .count();
    let tail = before[head..]
        .iter()
        .rev()
        .zip(after[head..].iter().rev())
        .take_while(|(a, b)| a == b)
        .count();
    let removed = &before[head..before.len().saturating_sub(tail)];
    let inserted = &after[head..after.len().saturating_sub(tail)];
    let erased = inserted.is_empty();
    let (glyphs, measure) = if erased {
        (removed, &before[..head + removed.len()])
    } else {
        (inserted, &after[..head + inserted.len()])
    };
    if glyphs.is_empty() {
        return None;
    }
    let mass = glyphs
        .iter()
        .rev()
        .take(8)
        .map(|ch| glyph_weight(*ch))
        .sum::<f32>()
        .max(0.25);
    let font = egui::TextStyle::Body.resolve(ui.style());
    let text = ui.painter().layout_no_wrap(
        measure.iter().collect::<String>(),
        font,
        Color32::PLACEHOLDER,
    );
    let rect = response.rect;
    let x = (rect.left() + 6.0 + text.size().x).clamp(rect.left() + 6.0, rect.right() - 6.0);
    let h = (rect.height() * 0.62).clamp(8.0, 18.0);
    let w = (4.0 + mass * 3.5).clamp(5.0, rect.width() * 0.35);
    let flux = if erased {
        TextFlux::Erase(mass)
    } else {
        TextFlux::Ink(mass)
    };
    Some(TextWake {
        rect: egui::Rect::from_center_size(egui::pos2(x, rect.center().y), egui::vec2(w, h)),
        flux,
    })
}

fn glyph_weight(ch: char) -> f32 {
    match ch {
        ' ' | '\t' => 0.35,
        'i' | 'l' | 'I' | '!' | '|' | '\'' | '`' | '.' | ',' | ':' | ';' => 0.55,
        'm' | 'w' | 'M' | 'W' | '@' | '#' | '%' | '&' => 1.35,
        'A'..='Z' | '0'..='9' => 1.1,
        _ if ch.is_ascii_punctuation() => 0.75,
        _ => 1.0,
    }
}

pub fn eyebrow(text: impl Into<String>) -> RichText {
    TypeRole::Label.text(text).color(MUTED)
}

pub fn title(text: impl Into<String>) -> RichText {
    TypeRole::Title.text(text).strong().color(TEXT)
}

pub fn muted(text: impl Into<String>) -> RichText {
    TypeRole::Body.text(text).color(MUTED)
}

pub fn note(ui: &mut egui::Ui, text: impl Into<String>) -> egui::Response {
    ui.add(egui::Label::new(muted(text)).wrap())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn activation_owns_only_fresh_unmodified_enter_or_space() {
        let stroke = |key, modifiers| {
            let ctx = egui::Context::default();
            ctx.run_ui(egui::RawInput::default(), |ui| {
                ui.button("command").request_focus();
            })
            .drop_without_applying_deltas();
            let mut activated = false;
            let mut retained = false;
            ctx.run_ui(
                egui::RawInput {
                    events: vec![
                        egui::Event::ModifiersChanged(modifiers),
                        egui::Event::Key {
                            key,
                            physical_key: Some(key),
                            pressed: true,
                            repeat: false,
                            modifiers,
                        },
                    ],
                    ..egui::RawInput::default()
                },
                |ui| {
                    let response = ui.button("command");
                    activated = exact_activation(ui, &response);
                    retained = ui.input(|input| {
                        input.events.iter().any(|event| {
                            matches!(
                                event,
                                egui::Event::Key {
                                    key: candidate,
                                    pressed: true,
                                    ..
                                } if *candidate == key
                            )
                        })
                    });
                },
            )
            .drop_without_applying_deltas();
            (activated, retained)
        };
        let repeat = |key| {
            let ctx = egui::Context::default();
            ctx.run_ui(egui::RawInput::default(), |ui| {
                ui.button("command").request_focus();
            })
            .drop_without_applying_deltas();
            let input = |repeat| egui::RawInput {
                events: vec![egui::Event::Key {
                    key,
                    physical_key: Some(key),
                    pressed: true,
                    repeat,
                    modifiers: egui::Modifiers::NONE,
                }],
                ..egui::RawInput::default()
            };
            let mut first = false;
            ctx.run_ui(input(false), |ui| {
                let response = ui.button("command");
                first = exact_activation(ui, &response);
            })
            .drop_without_applying_deltas();
            let mut repeated = true;
            let mut retained = true;
            ctx.run_ui(input(true), |ui| {
                let response = ui.button("command");
                repeated = exact_activation(ui, &response);
                retained = ui.input(|input| input.key_pressed(key));
            })
            .drop_without_applying_deltas();
            (first, repeated, retained)
        };

        for key in [egui::Key::Enter, egui::Key::Space] {
            assert_eq!(stroke(key, egui::Modifiers::NONE), (true, false));
            assert_eq!(stroke(key, egui::Modifiers::SHIFT), (false, true));
            assert_eq!(repeat(key), (true, false, false));
        }
    }

    #[test]
    fn accessibility_click_survives_an_unrelated_modified_activation_key() {
        let ctx = egui::Context::default();
        let mut id = egui::Id::NULL;
        ctx.run_ui(egui::RawInput::default(), |ui| {
            id = ui.button("command").id;
        })
        .drop_without_applying_deltas();
        let modifiers = egui::Modifiers::SHIFT;
        let input = egui::RawInput {
            events: vec![
                egui::Event::ModifiersChanged(modifiers),
                egui::Event::AccessKitActionRequest(egui::accesskit::ActionRequest {
                    action: egui::accesskit::Action::Click,
                    target_tree: egui::accesskit::TreeId::ROOT,
                    target_node: id.accesskit_id(),
                    data: None,
                }),
                egui::Event::Key {
                    key: egui::Key::Space,
                    physical_key: Some(egui::Key::Space),
                    pressed: true,
                    repeat: false,
                    modifiers,
                },
            ],
            ..egui::RawInput::default()
        };
        let mut activated = false;
        ctx.run_ui(input, |ui| {
            let response = ui.button("command");
            activated = exact_activation(ui, &response);
        })
        .drop_without_applying_deltas();

        assert!(activated);
        assert!(ctx.input(|input| input.key_pressed(egui::Key::Space)));
    }

    #[test]
    fn background_accessibility_click_cannot_pierce_a_modal_layer() {
        let ctx = egui::Context::default();
        let modal = || egui::Modal::new(egui::Id::new("activation-barrier"));
        let mut id = egui::Id::NULL;
        ctx.run_ui(egui::RawInput::default(), |ui| {
            id = ui.button("command").id;
            let _modal = modal().show(ui.ctx(), |ui| ui.label("modal"));
        })
        .drop_without_applying_deltas();
        let input = egui::RawInput {
            events: vec![egui::Event::AccessKitActionRequest(
                egui::accesskit::ActionRequest {
                    action: egui::accesskit::Action::Click,
                    target_tree: egui::accesskit::TreeId::ROOT,
                    target_node: id.accesskit_id(),
                    data: None,
                },
            )],
            ..egui::RawInput::default()
        };
        let mut activated = true;
        ctx.run_ui(input, |ui| {
            let response = ui.button("command");
            activated = exact_activation(ui, &response);
            let _modal = modal().show(ui.ctx(), |ui| ui.label("modal"));
        })
        .drop_without_applying_deltas();

        assert!(!activated);
    }
}
